var Rules = {
	SUBMERGED: 20,
	SUFFOCATE_CHANCE: 0.2,
	SEAWEED_CHANCE: 0.2,
	SEAWEED_LENGTH: [2, 6],
	SEAWEED_HEAL: 1,
	BUBBLE_COUNT: [5, 15],
	BUBBLE_RESTORE: 5,
	QUESTS: 12,
	ROD_LENGTH: 4,
	ROD_SHOW_CHANCE: 0.1,
	ROD_HIDE_CHANCE: 0.4,
	COMBAT_STDDEV: 2,
	ITEM_CHANCE: 0.4
}
